spring.datasource.url=jdbc:postgresql://localhost:5433/messanger_db
spring.datasource.username=postgres
spring.datasource.password=6353642
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong123
jwt.expiration=3600000