spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=myuser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
<<<<<<< HEAD

=======
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
>>>>>>> 9410c15ddc0611fbefd08dffb5ddc5972c607aec

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong123
jwt.expiration=3600000